#!/bin/bash
. DBmenu

connect-db()
{
read -p "enter database name you want to connect: " DBN
DB_path="$DBs/$DBN"
if [ -d "$DB_path" ]; then
         cd "$DB_path"
         echo "connected to $DBN "
         DBmenu
else
         echo "database name doesn't exist"
fi
}

