#!/bin/bash
. DBmenu

connect-db() {
    read -p "Enter the database name you want to connect to: " DBN
    DB_path="$DBs/$DBN"
    
    if [ -d "$DB_path" ]; then
        cd "$DB_path"
        echo "Connected to $DBN"
	DBmenu
else
        echo "Database name doesn't exist"
    fi
}


