#!/bin/bash

create-db()
{
read -p "enter the name of database :" name
db_path="$DBs/$name"
if [ -d "$db_path" ] || [ -z "$name" ] ; then
	echo "database $name already exists"
else
	mkdir -p "$db_path"
	echo "database created successfully"
fi
menu 
}
