#!/bin/bash

create-table () 
{

    read -p "Enter table name: " tablename
    if [ -f "$tablename" ]; then
        echo "Table $tablename already exists."
else
    touch "$tablename"
    fi 
    metadata="$tablename.metadata"
 touch "$metadata"
    read -p "Enter number of columns: " column_n
if [[ "$column_n" != [1-9] ]] || [ "$coulmn_n" -le 0 ]; then
	echo "invalid number of columns"
	return 
fi
echo "Table: $tablename" > "$metadata"
echo "columns:" >> "$metadata"
columns=()
    for ((i=1; i<=column_n; i++))
    do
        read -p "Enter column $i name: " column_name
        if [ -z "$column_name" ]; then 
		echo "column name can not be empty"
		return
	fi
	columns+=("$column_name")
	echo "$column_name" >> "$metadata"
done

#create table header using the column name that the user enters
header="+"
header_line="|"
for column in "${columns[@]}"
do
	header+=$(printf '%-s+' "---------")
	header_line+=$(printf '%-s |' "$column")
done
echo "table '$tablename' created successfully in database '$DBN'"
DBmenu
}





