#!/bin/bash

create-table () {
    read -p "Enter table name: " tablename
    if [ -f "$tablename" ]; then
        echo "Table $tablename already exists."
        return
    fi

    read -p "Enter number of columns: " column_n
    cl_names=()
    cl_datatypes=()

    for ((i=1; i<=column_n; i++))
    do
        read -p "Enter column $i name: " column_name
        cl_names+=("$column_name")
        read -p "Enter data type for $column_name (int, string): " dt
        cl_datatypes+=("$dt")
    done

   
    echo "${cl_names[*]}" > "$tablename"
    echo "${cl_datatypes[*]}" >> "$tablename"

    echo "Table $tablename created successfully with columns: ${cl_names[*]}"

    DBmenu
}



