#!/bin/bash 
source create-table
. list-tables
source drop-table
. insert
source select-table
source delete-table
DBmenu()
{
echo "1- create table "
echo "2- list tables"
echo "3- drop table"
echo "4- insert into tables"
echo "5- select table"
echo "6- delete from table"
echo "7- update table"
echo "8- back to menu"
read -p "enter your choice : " ch
case $ch in 
         "1")create-table;;
	 "2")list-tables;;
	 "3")drop-table;;
	 "4")insert;;
	 "5")select-table;;
	 "6")delete-table;;
	 "7")update-table;;
	 "8")menu;;
	 *) echo "try again";;
esac
}
